version: 2
updates:
  - package-ecosystem: "npm" # or "pip", "maven", etc.
    directory: "/" # location of package manifest
    schedule:
      interval: "daily" # options: "daily", "weekly", "monthly"
